spring.application.name=hotel

# Koneksi ke Database MySQL (Pastikan XAMPP / MySQL Anda sudah menyala)
spring.datasource.url=jdbc:mysql://localhost:3306/uas_hotel?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Setelan Hibernate untuk membuat tabel otomatis dari Class Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Ganti port agar tidak bentrok
server.port=8084